### ISSUE TITLE
object picking demo

### ISSUE THREAD

**Issue by lonnietc** [RolandKoenig/SeeingSharp2#10]
Hello,

Is there any type of object picking or selecting demo?

**Comment by RolandKoenig** [comment]
I've updated Seeing# so that all views provide the PickObjectMethod directly. Also, when using this method, you don't need to care about pixel/dip conversion, because the method does all the magic behind.
There is also a sample using WinUI 3 here: https://github.com/RolandKoenig/HappyCoding/tree/main/2022/HappyCoding.SeeingSharp2WithPicking/HappyCoding.SeeingSharp2WithPicking
