### ISSUE TITLE
Flickering Refresh Issue

### ISSUE THREAD

**Issue by axel578** [RolandKoenig/SeeingSharp2#11]
Hello !
I have an issue with the 3D viewer, any time I try to move or rotate in the scene, the whole scene gets updated 1/5 of the time with a lot of lag (the bug still appears for version 0.8 and 0.9 ). I don't manage any event on top or on the 3D viewer itself that could cause that kind of systematic refresh. The way it flickers is whenever I move, the scene gets whipped out and everything appear suddenly after ). I have the latest nvidia graphic driver, rtx 3070 on laptop.

I have a previous version of my software that worked perfectly and suddenly the bug appears with no changes to the program.

**Comment by RolandKoenig** [comment]
Hi 
can you give me more details about the issue?
 - What UI Framework do you use? (WPF, UWP, WinUI, WinForms)
 - How big is your scene (count of objects, count of triangles per object, etc.)?

Flickering can have a few issues
 - The scene was updated (new objects created, current objects changed etc.). Behind the scene, Seeing# processes all changes on objects / geometry and culling beside rendering the last state of the scene. This leads to the fact that changes are visible after one or two frames after you trigger a change operation (like Scene.ManipulateSceneAsync...)
 - You may get a short flickering after changing screen resolution of the view (resize the window, etc.). This is because after changing the resoultion, Seeing# has to recreate some resources for rendering 3D content into the view
 - In some cases it may be also caused by the graphics driver. You can assign the software rendering device to the view to ensure that no hardware is involved in rendering. Try something like this: this.CtrlView3D.Device = GraphicsCore.Current.DefaultSoftwareDevice
 
 The last option, assigning of a software device is more for experimenting. See this article for more info about the software device: https://github.com/RolandKoenig/SeeingSharp2/wiki/CPU-utilization-on-software-rendering

**Comment by axel588** [comment]
Sorry for the late answer, it was a driver issue
